[project]
name = "fides"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "azure-identity>=1.23.0",
    "docstring-parser>=0.16",
    "openai>=1.82.0",
    "python-dotenv>=1.1.0",
    "ipykernel>=6.29.5",
]
